### ISSUE TITLE
Store password hashes rather than storing them in plain text.

### ISSUE THREAD

**Issue by weibeu** [thec0sm0s/cosnote#1]
https://github.com/thec0sm0s/instant-notes/blob/2902d06b9c33a750ab238bb660c910bdfa7ad2f7/flask_app.py#L64-L76

**Comment by Bhavik-Ardeshna** [comment]
Hey @thec0sm0s I really want to work on this and this my first contribution plz assign me this issue

**Comment by weibeu** [comment]
Okay sure thing thanks for considering it. You may join our [Discord community](https://discord.gg/7CrQEyP) if you want join us on this event.

**Comment by Bhavik-Ardeshna** [comment]
Plz guide because it's my first contribution and I joined the Discord

**Comment by MohammedBajuaifer** [comment]
Would like to work on this, is it still open?

**Comment by weibeu** [comment]
@MohammedBajuaifer I have assigned this to bhavik. THere are few issues still open and I will add few more. So check my profile, and see if any issue listed there interests you or just wait I might post few more

**Comment by MohammedBajuaifer** [comment]
Thanks @thec0sm0s, i'll look around!

**Comment by williamhatcher** [comment]
@MohammedBajuaifer @thec0sm0s I'd like to contribute some to this as well.
