### ISSUE TITLE
Allow same user to create multiple notes.

### ISSUE THREAD

**Issue by weibeu** [thec0sm0s/cosnote#3]
https://github.com/thec0sm0s/instant-notes/blob/4333b5566dc81e66eb0aa3eb203431e355601932/flask_app.py#L74-L76

**Comment by Bhavik-Ardeshna** [comment]
hey assign me i want to work on this plz
!!

**Comment by weibeu** [comment]
@Bhavik-Ardeshna Sure you may start with it!
